---
title: "Homework 5"
author: "Danara flores"
date: "2024-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = FALSE, warning = FALSE)
library(tidyverse)
library(ggthemes)

```

```{r}
homicides<- read.csv("/Users/danaraflores/Desktop/R programing 535/Homework 5/hw 5/data/homicide-data.csv")
city_homicides <- homicides %>%
  filter(city == "Baltimore")%>%
  mutate( reported_date = ymd(reported_date),
          month = month(reported_date),
          year = year(reported_date),
          year_mon = paste(year,month, sep = "-")) #Added here, could put it in to the bottom monthly homs

#need counts of homicides per month 


```

```{r monthly_homicides}
MD_homs<- city_homicides %>% 
  group_by(year,month, year_mon) %>%
  summarize(total = n()) %>% 
   mutate(year_mon = ym(year_mon),  #changed to date here to make the graph better
          season = if_else(month >= 5 & month <= 10, "Summer", "Winter"),  
          season = fct_relevel(season, c("Summer", "Winter")))
```

```{r plot, fig.width= 15, fig.height= 5}
#work with Plot
plot1<-  ggplot( data = MD_homs)+
  geom_bar(aes(x= year_mon, weight = total, fill= season))+ #fix here to add in the totals per month
  geom_smooth(aes(x = year_mon, y = total), color = "blue")+
  scale_fill_manual(name = " ", values = c("Winter" = "slategray1",
                               "Summer" = "gray87"))+
  theme_dark()+
  ggtitle("Homicides in Baltimore, MD")+
  xlab("Date")+
  ylab("Monthly homicides")
```


```{r find_freddie}
freddie<-city_homicides %>% 
  filter(victim_last == "GREY") %>% #all the grays with an A are not freddie, has to use grey with E
  mutate(date_arrest = as.Date(reported_date))

#helped find the arrest date or reported date to be 2015- 04 -30.  ymd

```

```{r add_freddie, fig.width= 15, fig.height= 3}

Freddie_plot<-  ggplot( data = MD_homs)+
  geom_bar(aes(x= year_mon, weight = total, fill= season))+ #fix here to add in the totals per month
  geom_smooth(aes(x = year_mon, y = total), color = "blue")+        #need to smooth this line out to better follow graph 
  scale_fill_manual(name = " ", values = c("Winter" = "slategray1",
                               "Summer" = "gray87"))+ #need to move legend to the bottom 
  theme_dark()+
  ggtitle("Homicides in Baltimore, MD")+
  xlab("Date")+
  ylab("Monthly homicides")+
  geom_vline(xintercept = as.Date(freddie$date_arrest), color = "red", linetype = 2, size = 2)+
  annotate("text",x = as.Date(freddie$date_arrest), y = 40, label = "Arrest of Freddie Grey", color = "white") +
  theme(legend.position = "bottom")




print(Freddie_plot)
```

